const listItems = [
  { id: 'complete-solution', text: 'Complete solution' },
  { id: 'fully-flexible', text: 'Fully flexible' },
  { id: 'advanced-controls', text: 'Advanced controls' },
  { id: 'secure-reliable', text: 'Secure and reliable' },
  { id: 'actionable-visibility', text: 'Actionable visibility' },
  { id: 'integrations', text: '100+ Integrations' },
  { id: 'ai-powered', text: 'AI powered' },
];

const dataList = [
  {
    id: 'complete-solution',
    smallHeading: 'Complete solution',
    heading: 'The everything app for work',
    text1: 'All the tools you need in one platform, boosting efficiency, enhancing visibility, and empowering everyone with data-driven decisions.',
    image1Path: '/manufacturer/layout-item.avif',
    card1Title: "Projects and Tasks",
    card1Descriptio: "Simplify project and task management, freeing up time to focus on what matters most.",
    image2Path: '/manufacturer/layout-item-block__graphic__27_.avif',
    card2Title: "Views and Dashboards",
    card2Descriptio: "Visualize work in 15+ views including list, board, gantt, with productivity analytics at your fingertips.",
    image3Path: '/manufacturer/layout-item-block__graphic__26_.avif',
    card3Title: "Docs and Whiteboards",
    card3Descriptio: "Create, share, and visualize plans with collaborative docs and fully-featured whiteboards.",
  },
  {
    id: 'fully-flexible',
    smallHeading: 'Fully flexible',
    heading: 'Perfectly fits all workflows',
    text1: 'ProductDB offers incredible flexibility that empowers teams to work in their own style, while seamlessly collaborating towards shared goals, all from a single platform.',
    image1Path: '/manufacturer/custom-workflows.avif',
    card1Title: "Custom workflows",
    card1Descriptio: "Designed for how teams want to work. No more workarounds or tradeoffs.",
    image2Path: '/manufacturer/custom-task-types.avif',
    card2Title: "Custom Task types",
    card2Descriptio: "Turn tasks into leads, tickets, and more, fitting the needs of any team.",
    image3Path: '/manufacturer/task-type-as-template.avif',
    card3Title: "Reusable templates",
    card3Descriptio: "Start with 100s of prebuilt templates, or build your own for repeated success.",
  },
  {
    id: 'advanced-controls',
    smallHeading: 'Advanced controls',
    heading: 'Manage controls and permissions',
    text1: 'Change permissions and security settings for guests, members, and admins. You control what users can and can\'t see or do for each level of your Workspace.',
    image1Path: '/manufacturer/secure-access.avif',
    card1Title: "Secure access",
    card1Descriptio: "Ensure authorized access with SSO, SAML, 2FA, all aligned with enterprise security standards.",
    image2Path: '/manufacturer/custom-permissions.avif',
    card2Title: "Custom permissions",
    card2Descriptio: "Design user roles with granular permissions, for precise control and access levels across the workspace.",
    image3Path: '/manufacturer/admin-management.avif',
    card3Title: "Admin management",
    card3Descriptio: "Equip admins with intuitive user access management and permissions, maximizing efficiency and operations.",
  },
  {
    id: 'secure-reliable',
    smallHeading: 'Secure and reliable',
    heading: 'Scale your enterprise confidently',
    text1: 'Your workspace is built with privacy, security, and data residency in mind, adapting to your ever-growing needs and challenges.',
    image1Path: '/manufacturer/monitoring-and-operations.avif',
    card1Title: "Monitoring and operations",
    card1Descriptio: "Effortlessly access audit logs, 24/7 monitoring, and comprehensive penetration testing, securing your data around the clock.",
    image2Path: '/manufacturer/regional-data-residency.avif',
    card2Title: "Regional data residency",
    card2Descriptio: "Choose from US, EU, or APAC data storage under Regional Data Residency, keeping your data secure within your chosen region.",
    image3Path: '/manufacturer/data-stays-yours.avif',
    card3Title: "Your data stays yours",
    card3Descriptio: "We collect just what's needed to support you and enhance our services, ensuring your data is never shared or sold.",
  },
  {
    id: 'actionable-visibility',
    smallHeading: 'Actionable visibility',
    heading: 'Visibility without busywork',
    text1: 'Whether your goal is greater efficiency or faster outcomes, you\'ll gain real-time insight and visibility into projects, people, and resources - fueling data-driven decisions.',
    image1Path: '/manufacturer/dashboards.avif',
    card1Title: "Dashboards",
    card1Descriptio: "See progress at a glance with dashboards across any team, project, or goal.",
    image2Path: '/manufacturer/analytics.avif',
    card2Title: "Analytics",
    card2Descriptio: "Make smarter decisions with real-time data and analytics support.",
    image3Path: '/manufacturer/goals-and-OKRs.avif',
    card3Title: "Goals and OKRs",
    card3Descriptio: "Keep teams aligned and moving forward with automated OKR tracking.",
  },
  {
    id: 'integrations',
    smallHeading: 'Integration',
    heading: 'Seamlessly connected',
    text1: 'Integrations',
    image1Path: '/manufacturer/integrations.avif',
    card1Title: "Integrations",
    card1Descriptio: "Instantly connect to Slack, Salesforce, GSuite, Github, and more.",
    image2Path: '/manufacturer/universal-search.avif',
    card2Title: "Universal Search",
    card2Descriptio: "Integrate with thousands of apps to automate work and reduce duplication.",
    image3Path: '/manufacturer/ProductDB-api.avif',
    card3Title: "ProductDB API",
    card3Descriptio: "Developers get full access to build custom apps and integrations.",
  },
  {
    id: 'ai-powered',
    smallHeading: 'ProductDB Brain',
    heading: 'AI-powered productivity',
    text1: 'Speed up and simplify work with the world\'s first neural network connecting tasks, docs, people, and all of your company’s knowledge with AI.',
    image1Path: '/manufacturer/ai-knowledge-manager.avif',
    card1Title: "AI Knowledge Manager™",
    card1Descriptio: "Ask questions and get answers from your docs, tasks, and projects.",
    image2Path: '/manufacturer/ai-project-manager.avif',
    card2Title: "AI Project Manager™",
    card2Descriptio: "A side-kick that manages and automates work such as updates.",
    image3Path: '/manufacturer/uptime.avifai-writer-for-work.avif',
    card3Title: "AI Writer for Work™",
    card3Descriptio: "Create content and reply quickly with an assistant tailored for work.",
  },
];




export { listItems, dataList };

