import {
  ArrowPathRoundedSquareIcon,
  CalendarDaysIcon,
  CalendarIcon,
  ChartBarIcon,
  ChatBubbleLeftIcon,
  CheckCircleIcon,
  CircleStackIcon,
  CodeBracketIcon,
  Cog6ToothIcon,
  ComputerDesktopIcon,
  DocumentArrowDownIcon,
  DocumentIcon,
  DocumentTextIcon,
  PencilIcon,
  PencilSquareIcon,
  RocketLaunchIcon,
  ChatBubbleBottomCenterTextIcon,
  ChatBubbleLeftRightIcon
} from "@heroicons/react/20/solid";

const featuresTabData = [
  {
    id: "tabOne",
    text: "Producent",
    icon: <CalendarIcon className="h-10 w-10" />,
    heading: "Deliver projects on time, every time",
    para: "  Get teams running more efficiently with a complete project management solution.",
    li1: "Reduce delivery time with custom templates",
    li2: "Track effort to impact with OKR planning",
    li3: "Manage complex projects at scale",
    image: "/home/featureCard/convene-headshot.png",
    name: "CONVENE",
    intro:
      "“ProductDB brings all of our teams together into one place so that they can stay on track, collaborate and communicate.”",
    li4: "Flexible workflows for every team",
    li4_Icon: <Cog6ToothIcon className="h-8 w-8 dark:text-white text-black" />,
    li5: "Tasks, docs, spreadsheets, and more",
    li5_Icon: <DocumentTextIcon className="h-8 w-8 dark:text-white text-black" />,
    li6: "Resource and workload optimization",
    li6_Icon: <CircleStackIcon className="h-8 w-8 dark:text-white text-black" />,
    li7: "Dashboards and insights",
    li7_Icon: <ComputerDesktopIcon className="h-8 w-8 dark:text-white text-black" />,
  },
  {
    id: "tabTwo",
    text: "Groothandel",
    icon: <ChatBubbleLeftRightIcon className="h-10 w-10" />,
    heading: "The complete marketing solution",
    para: "The all-in-one work hub for modern marketing teams, completely free.",
    li1: "Build visual plans that keep teams on track",
    li2: "Fast track delivery with templates and calendars",
    li3: "Leverage AI to accelerate content creation",
    image: "/home/featureCard/finastra-headshot.png",
    name: "FINASTRA",
    intro:
      "“ProductDB enables us to optimize resources more effectively and align our GTM across the business.”",
    li4: "Flexible workflows for every team",
    li4_Icon: <Cog6ToothIcon className="h-8 w-8 dark:text-white text-black" />,
    li5: "Visual roadmaps and calendars",
    li5_Icon: <CalendarDaysIcon className="h-8 w-8 dark:text-white text-black" />,
    li6: "AI-powered writing support",
    li6_Icon: <PencilSquareIcon className="h-8 w-8 dark:text-white text-black" />,
    li7: "Tasks, docs, spreadsheets, and more",
    li7_Icon: <DocumentTextIcon className="h-8 w-8 dark:text-white text-black" />,
  },
  {
    id: "tabThree",
    text: "Retail",
    icon: <ComputerDesktopIcon className="h-10 w-10" />,
    heading: "Plan, build, & ship, all in one place",
    para: "The only all-in-one product management toolkit, completely free.",
    li1: "Get flexible agile workflows for fast moving teams",
    li2: "Reduce development time with visual roadmaps",
    li3: "Communicate product updates and priorities",
    image: "/home/featureCard/lulu-headshot.png",
    name: "LuLu",
    intro:
      "“With ProductDB, we’ve regained hours of wasted time compared to Jira. Even better, we’ve accelerated our product releases.”",
    li4: "Agile task and issue management",
    li4_Icon: <RocketLaunchIcon className="h-8 w-8 dark:text-white text-black" />,
    li5: "Insights and dashboards",
    li5_Icon: <ComputerDesktopIcon className="h-8 w-8 dark:text-white text-black" />,
    li6: "Whiteboards and diagramming",
    li6_Icon: <DocumentIcon className="h-8 w-8 dark:text-white text-black" />,
    li7: "Docs, spreadsheets, and more",
    li7_Icon: <DocumentTextIcon className="h-8 w-8 dark:text-white text-black" />,
  },
  {
    id: "tabFour",
    text: "Webshop",
    icon: <CodeBracketIcon className="h-10 w-10" />,
    heading: "More building, less busy work",
    para: "Your end-to-end product development platform, completely free.",
    li1: "Get flexible agile workflows for fast moving teams",
    li2: "Track dependencies and resources across squads",
    li3: "Automate and integrate across your tech stack",
    image: "/home/featureCard/pressed-headshot.png",
    name: "pressed",
    intro:
      "“ProductDB keeps our engineering department hyper-focused on the right initiatives.”",
    li4: "Agile task and issue management",
    li4_Icon: <RocketLaunchIcon className="h-8 w-8 dark:text-white text-black" />,
    li5: "Insights and dashboards",
    li5_Icon: <ComputerDesktopIcon className="h-8 w-8 dark:text-white text-black" />,
    li6: "Seamless 2-way Git sync",
    li6_Icon: <ArrowPathRoundedSquareIcon className="h-8 w-8 dark:text-white text-black" />,
    li7: "Docs, spreadsheets, and more",
    li7_Icon: <DocumentTextIcon className="h-8 w-8 dark:text-white text-black" />,
  },
  {
    id: "tabFive",
    text: "Technical",
    icon: <PencilSquareIcon className="h-10 w-10" />,
    heading: "The complete agency solution",
    para: "Deliver higher quality client work that's more profitable, faster.",
    li1: "Visualize projects, progress, and teamwork",
    li2: "Speed up collaboration and feedback cycles",
    li3: "Optimize resources and productivity",
    image: "/home/featureCard/hawkemedia-headshot.png",
    name: "hawkemedia",
    intro:
      "“Our executive team decreased project delay by over 70% throughout our first year using ProductDB.”",
    li4: "Flexible workflows for any project",
    li4_Icon: <Cog6ToothIcon className="h-8 w-8 dark:text-white text-black" />,
    li5: "Tasks, docs, spreadsheets, and more",
    li5_Icon: <DocumentTextIcon className="h-8 w-8 dark:text-white text-black" />,
    li6: "Resource and workload optimization",
    li6_Icon: <CircleStackIcon className="h-8 w-8 dark:text-white text-black" />,
    li7: "Dashboards and insights",
    li7_Icon: <ComputerDesktopIcon className="h-8 w-8 dark:text-white text-black" />,
  },
];

export default featuresTabData;
